### ISSUE TITLE
Summits that are too close

### ISSUE THREAD

**Issue by mehrankr** [macs3-project/MACS#110]
Hello MACS community,

Running MACS2 with --call-summits I found that often the summits of a single narrowpeak can be too close; as close as 2bp. In all of ENCODE dataset for example there is  62 such cases.

This complicates the interpretation of the summits and I was wondering to ask if this is a problem that other people have seen and might have an opinion on it.

Example of a command I use:
macs2 callpeak -t ENCSR000AUE_ENCFF000AHP_Rep1.bam ENCSR000AUE_ENCFF000AHR_Rep2.bam --nomodel --qvalue 0.001 -f BAM -g hs -n BradleyBernstein-Broad_A549_CTCF_CHEBI-41879-dexamethasone-1-hour-nM-100_No-Control_ENCSR000AUE --outdir MACS2/BradleyBernstein-Broad_A549_CTCF_CHEBI-41879-dexamethasone-1-hour-nM-100_No-Control_ENCSR000AUE --call-summits --verbose 2

Thanks
Mehran

**Comment by philippadoherty** [comment]
Closing this issue as "stale" due to inactivity.
