### ISSUE TITLE
usage of --slocal and --llocal

### ISSUE THREAD

**Issue by emancera** [macs3-project/MACS#111]
I am trying to run macs so that it does NOT consider the background lambda (λBG) when getting the maximum lambda to calculate the local lambda. I just want to use the 1kb, 5kb and 10kb window lambdas when calculating the local lambda. Is this possible using --slocal and --llocal?

From the explanation of --slocal and --llocal it is not clear whether when you specify these parameter the background lambda (λBG) is still considered when calculating the local lambda.

Thanks for the help,

E

**Comment by taoliu** [comment]
You can do so by utilizing the subcommands in MACS2. I have updated MACS2 codes to enable certain functions in subcommands (e8da469). And I am currently updating the wiki page: https://github.com/taoliu/MACS/wiki/Call-peaks-using-MACS2-subcommands

**Comment by taoliu** [comment]
Hi Eugenio, please check the wiki page https://github.com/taoliu/MACS/wiki/Advanced%3A-Call-peaks-using-MACS2-subcommands Especially the section about how to build local bias track.

**Comment by emancera** [comment]
Thank you very much again, I will have a look.

Eugenio

**Comment by taoliu** [comment]
@emancera Don't forget to update your MACS2 to the current version on github -- you also need cython to install from the source codes on github. Some of the functions mentioned in the wiki page are not available in older version. Will release a MACS2 package on PyPI website in days.
