### ISSUE TITLE
Is the peak height fold change from two different peak calling events comparable?

### ISSUE THREAD

**Issue by JingyiTang** [macs3-project/MACS#119]
Dear Scientist Tao,

Hi! I am just wondering whether I could directly compare the peak height from fold change generated from two different peak calling events, such as H3K4me3 ChIP from one condition and H3K4me3 ChIP from another condition (each has its own input control ChIP)?

Similarly, could I compare H3K4me3 ChIP from one biological replicate and H3K4me3 ChIP from another biological replicate (each has its own input control ChIP)?

I just realise that MACS can identify differential binding regions. I am not sure whether you have heard about csaw (https://bioconductor.org/packages/release/bioc/html/csaw.html), but if you do, could you have some comments about MACS and csaw in identifying differential binding regions? 

Thanks so much in advance!

Jingyi from the University of Melbourne

**Comment by philippadoherty** [comment]
Closing this issue as "stale" due to inactivity.
