### ISSUE TITLE
Chromosome by chromosome bias on peakcalling

### ISSUE THREAD

**Issue by richjoh** [macs3-project/MACS#121]
Hi Tao

I am relatively new to Macs2.  Although it is sensitive enough pick up many picks, one thing that I noticed is that the number of peak can vary a lot from one chromosome to another.  

Peaks from my ChIP-seq data is not very strong (-q 0.1 --broad --llocal 100000).  For many peak calling comparison, values of fold enrichment are very different between chromosomes.  For example, I sometimes get 50 peaks on chromosome I (with fold enrichment <1.2), no peaks on chromosome II and 100 peaks on chromosome III (with fold enrichment~3).  Therefore, it looks like there might be systematic bias when calculating fold enrichment for each chromosome.

Is there anyway to get around this issue?  From my dataset, I expect more less equal distribution of many weak peaks throughout the genome (confirmed by visual inspection of ChIP-seq profiles).

Thanks,
Richard

**Comment by philippadoherty** [comment]
Closing this issue as "stale" due to inactivity.
