### ISSUE TITLE
MACS2 for Nicotiana tabacum

### ISSUE THREAD

**Issue by februaryfang** [macs3-project/MACS#126]
Hi Tao,
I want to analysis my Nicotiana tabacum chip-seq data with MACS2.My sequence type is single-ended 50. The 'genome' I used is composed of scaffolds,"ftp://ftp.solgenomics.net/genomes/Nicotiana_tabacum/assembly/Ntab-K326_AWOJ-SS.fa.gz".
Can I properly analyzed it in this situation ? How long the 'GSIZE' I should set ?

**Comment by philippadoherty** [comment]
Closing this issue as "stale" due to inactivity.
