### ISSUE TITLE
threshold of macs2 for bdgbroadcall

### ISSUE THREAD

**Issue by dguowfu** [macs3-project/MACS#127]
Dear Dr. Liu,

I used the following command to conduct peak calling of my .bedGraph file. I am wondering if there is a default value of the parameter -c, which, from my understanding, is the cutoff of  maxHeightPixels of a region. Here I randomly chosen -c = 5. Thanks!
macs2 bdgbroadcall -i input.bedGraph -o output.bed -c 5

Maggie at WFU

**Comment by philippadoherty** [comment]
Closing this issue as "stale" due to inactivity.
