### ISSUE TITLE
Difference b/w version 2.1.0.20150731 and version 2.1.1.20160309

### ISSUE THREAD

**Issue by aarthi-mohan** [macs3-project/MACS#131]
Hi,

I recently updated MACS2 using 'pip', and re-run the peak calling. I found that the broad peak call numbers have increased so much. How is this?

I have used the same parameters in both the run, but still get different peak numbers. There is also a change in the number of narrow peaks, but not this dramatic.  I use BAMPE, since  my data is paired-end. 

**# broad peaks b/w the two version:**
 sample  v2.1.0  v2.1.1
Sample1  914      2250 
Sampe2   5          3860 

What is the difference in the broad peak calling between the two versions?

Appreciate your help!

Thanks,
Aarthi

**Comment by philippadoherty** [comment]
Closing this issue as stale, due to inactivity. Please feel free to re-open this with a comment.
