### ISSUE TITLE
ImportError: No module named MACS2.Constants

### ISSUE THREAD

**Issue by icTAIR** [macs3-project/MACS#132]
Hi Tao Liu,

When I run MACS2, there is en error.
Traceback (most recent call last):
  File "/lorax/Software/MACS2-2.1.0/bin/macs2", line 30, in <module>
    from MACS2.Constants import *
ImportError: No module named MACS2.Constants

And before I run MACS2, I used two commends to define the python:
export PYTHONPATH=$HOME/lib/python2.7/site-packages/:$PYTHONPATH
export PATH=$HOME/bin/:$PATH
Then, I run MACS2:
/lorax/Software/MACS2-2.1.0/bin/macs2 callpeak -t xxx.bam -f BAM -g 3.2e9 -n xxx -B -q 0.01.

Thank you very much!

**Comment by taoliu** [comment]
Since you have add the "$HOME/bin/" to your $PATH, you can simply run 'macs2' or '$HOME/bin/macs2' in command line, after you successfully installed MACS2. I guess the "/lorax/Software/MACS2-2.1.0/" directory is where the source codes are. Do not run 'macs2' from the source code folder.

**Comment by yamzaleg** [comment]
Hello Tao.

I'm having the same issue with macs2. Whenever I just type macs2 (in any directory) I get:
 jamzaleg84@itg:~ macs2
Traceback (most recent call last):
  File "/home/jamzaleg84/bin/macs2", line 31, in <module>
    from MACS2.Constants import *
ImportError: No module named MACS2.Constants

I tried exporting the python path as done above, but It still isn't working.

Yonatan

**Comment by philippadoherty** [comment]
Closing this issue as stale, due to inactivity. Please feel free to re-open this with a comment.
