### ISSUE TITLE
sorted bam files

### ISSUE THREAD

**Issue by serkanerdin** [macs3-project/MACS#133]
I was wondering when you run MACS2 with BAMPE option, does it matter how to sort BAM files?
or is it best to run with unsorted bams? I saw that people reported unmatched results with coordinate and name sorted bams before.

**Comment by taoliu** [comment]
Now this issue should have been fixed in the version 2.1.0 20150731. If you still see inconsistent results, please let me know.

**Comment by philippadoherty** [comment]
Closing this issue as stale, due to inactivity. Please feel free to re-open this with a comment.
