### ISSUE TITLE
option --linking-cutoff is not implemented for --broad ?

### ISSUE THREAD

**Issue by carl-** [macs3-project/MACS#135]
Hi, tao,

Is the option --linking-cutoff implemented for broad peak calling in macs2 now?

I found that option in the help message of callpeak sub command but got an error if i enable it
macs2: error: unrecognized arguments: --linking-cutoff

**Comment by taoliu** [comment]
@carl-, it's the '--broad-cutoff' option for 'macs2 callpeak'; or can be '--cutoff-link' option in 'macs2 bdgbroadcall;

**Comment by philippadoherty** [comment]
Closing this issue as stale, due to inactivity. Please feel free to re-open this with a comment.
