### ISSUE TITLE
macs2 command choice when call broad peak 

### ISSUE THREAD

**Issue by yinyao41** [macs3-project/MACS#137]
Hi @taoliu 
  Using  macs2 to call broad peak ,how to decide the command " --nomodel , --extsize , --broad-cutoff "  to use ?
The command line  : macs2 callpeak -t "$IP_bam" -c "$Input_bam" --broad -g hs --broad-cutoff 0.1 -n "${file}"-A-NC-broad-nomodel --nomodel --extsize 146 
 or 
macs2 callpeak -t "$IP_bam" -c "$Input_bam" --broad -g hs -n "${file}"-A-NC-broad
could you explain the difference of these two command line

**Comment by philippadoherty** [comment]
Closing this issue as stale, due to inactivity. Please feel free to re-open this with a comment.
