### ISSUE TITLE
Does not throw error when files don't have read permissions

### ISSUE THREAD

**Issue by snystrom** [macs3-project/MACS#139]
Macs will succesfully run on files the user does not have read permission on and will create empty output files. My guess is the program interprets them as being empty instead of being unable to be opened.  Either some sort of check for access permissions or a flag in the stdError/stdOut if an empty file is detected would be great.

**Comment by taoliu** [comment]
Thanks for reporting the issue! I think MACS2 should throw a "IOError: [Errno 13] Permission denied", instead of processing them as empty files. Could you share me the version of MACS2 you used, the command lines, and the permissions of your input files, so that I can reproduce such issue?

**Comment by philippadoherty** [comment]
Closing this issue as stale, due to inactivity. Please feel free to re-open this with a comment.
