### ISSUE TITLE
I have some problems to deal with macs.

### ISSUE THREAD

**Issue by jamespotter** [macs3-project/MACS#141]
Hello,

I recently followed the protocol of m6A sequencing which is published in 2013 (Dominissini, Dan, et al. "Transcriptome-wide mapping of N6-methyladenosine by m6A-seq based on immunocapturing and massively parallel sequencing." Nature protocols 8.1 (2013): 176-189.). And I got two problems. Those troubles are found in running macs. At first, according to above reference paper, they used "--to-small" parameter. However, in my case, my computer said there isn't such option called "--to-small". Next, if I typed like this.
$macs14 -t IP.sam -c Input.sam --name=m6A --format="SAM" --gsize=282000000 --tsize=36 --nomodel --shiftsize=50 -w -S 2 > macs.out &
Then, there are some errors found like as follows.

**# ARGUMENTS LIST:**

**# name = m6A**

**# format = SAM**

**# ChIP-seq file = IP.sam**

**# control file = Input.sam**

**# effective genome size = 2.82e+08**

**# band width = 300**

**# model fold = 10,30**

**# pvalue cutoff = 1.00e-05**

**# Large dataset will be scaled towards smaller dataset.**

**# Range for calculating regional lambda is: 1000 bps and 10000 bps**

INFO @ Wed, 17 Aug 2016 10:26:59: #1 read tag files...

INFO @ Wed, 17 Aug 2016 10:26:59: #1 read treatment tags...

Traceback (most recent call last):

File "/usr/local/bin/macs14", line 366, in <module> main()

File "/usr/local/bin/macs14", line 60, in main (treat, control) = load_tag_files_options (options)

File "/usr/local/bin/macs14", line 335, in load_tag_files_options ttsize = tp.tsize()

File "/usr/local/lib/python2.7/dist-packages/MACS14/IO/Parser.py", line 647, in tsize (chromosome,fpos,strand) = self.__fw_parse_line(thisline)

File "/usr/local/lib/python2.7/dist-packages/MACS14/IO/Parser.py", line 684, in __fw_parse_line bwflag = int(thisfields[1])

ValueError: invalid literal for int() with base 10: '-'

This is my first time to use macs, so if anyone helps me, I'll very appreciate it.

Thank you

**Comment by taoliu** [comment]
It seems related to MACS version 1 only.  The '--to-small' option is now a default in MACS 1.4, so there is no need to specify it. The error you saw seems to be a format error in the IP.sam file. I recommend you download their FASTQ file, align the sequences to reference genome using standard tool such as BWA or BOWTIE to get BAM file instead.

**Comment by philippadoherty** [comment]
Closing this issue as stale, due to inactivity. Please feel free to re-open this with a comment.
