### ISSUE TITLE
ValueError: cannot resize this array: it does not own its data

### ISSUE THREAD

**Issue by antonkratz** [macs3-project/MACS#146]
I am invoking macs2 like this: `time macs2 callpeak -t paired.srtd.bam --outdir out2`.
This is on asorted bam file containing paired end data.
I am using `macs2 2.1.1.20160309`.
This leads to an error `ValueError: cannot resize this array: it does not own its data`:
How can I proceed from here? I would like to call peaks on this bam file.

> Traceback (most recent call last):
>   File "/usr/local/bin/macs2", line 617, in <module>
>     main()
>   File "/usr/local/bin/macs2", line 57, in main
>     run( args )
>   File "/usr/local/lib/python2.7/dist-packages/MACS2/callpeak_cmd.py", line 264, in run
>     peakdetect.call_peaks()
>   File "MACS2/PeakDetect.pyx", line 110, in MACS2.PeakDetect.PeakDetect.call_peaks (MACS2/PeakDetect.c:1665)
>   File "MACS2/PeakDetect.pyx", line 364, in MACS2.PeakDetect.PeakDetect.__call_peaks_wo_control (MACS2/PeakDetect.c:4714)
>   File "MACS2/IO/CallPeakUnit.pyx", line 861, in MACS2.IO.CallPeakUnit.CallerFromAlignments.call_peaks (MACS2/IO/CallPeakUnit.c:12334)
>   File "MACS2/IO/CallPeakUnit.pyx", line 915, in MACS2.IO.CallPeakUnit.CallerFromAlignments.call_peaks (MACS2/IO/CallPeakUnit.c:12086)
>   File "MACS2/IO/CallPeakUnit.pyx", line 970, in MACS2.IO.CallPeakUnit.CallerFromAlignments.__chrom_call_peak_using_certain_criteria (MACS2/IO/CallPeakUnit.c:12492)
>   File "MACS2/IO/CallPeakUnit.pyx", line 475, in MACS2.IO.CallPeakUnit.CallerFromAlignments.__pileup_treat_ctrl_a_chromosome (MACS2/IO/CallPeakUnit.c:6861)
> ValueError: cannot resize this array: it does not own its data

**Comment by taoliu** [comment]
Refer to #122

**Comment by philippadoherty** [comment]
Closing this issue as stale, due to inactivity. Please feel free to re-open this with a comment.
