### ISSUE TITLE
pvalue cutoff and qvalue cutoff

### ISSUE THREAD

**Issue by liulingnovo** [macs3-project/MACS#159]
Dear, tao,

     I have a question about the output files: "NAME_peaks.xls" "NAME_peaks.narrowPeak".  
     Is it true that when **pvalue** cutoff was specified, then the "qvalue" will not be calculated and should be reported as "-1" in the final outpu, such as  "NAME_peaks.xls" "NAME_peaks.narrowPeak"?
     But, in my test, the **pvalue** was specified, however, in the output files, there were still show "-log10(qvalue)" which is not reported as "-1".   Actually, the results seems no differents from "qvalue" cutoff was specified in form.

Thank you very much for all your help,
Ling.

**Comment by taoliu** [comment]
Hi Ling,

In the current version, even if you specify -p for 'callpeak' subcommand, q-values will still be calculated and reported.

Best,
Tao

**Comment by aneeshbio** [comment]
Hi taoliu,
I have question on callpeak cutoffanalysis. After cutoffanalysis I am getting table with pscores and qscores and corresponding peaks. But, Here my question is how to set p-score as p-value in command line.  In the below example I want to set p-score of 4.80 as my p-value.  So how to set in command line. 
If i am setting as 0.0000000048 i am getting different number of peaks than the expected. So how may decimals i have to keep.
pscore	qscore	npeaks	lpeaks	avelpeak
9.90	8.01	37334	75404747	2019.00
9.60	7.73	37493	76048652	2028.00
9.30	7.44	38264	78342303	2047.00
9.00	7.20	43227	89767548	2076.00
8.70	6.91	43919	92016391	2095.00
8.40	6.64	46849	99494870	2123.00
8.10	6.36	47875	102778215	2146.00
7.80	6.09	50826	110710731	2178.00
7.50	5.81	51527	113595025	2204.00
7.20	5.56	57587	130025485	2257.00
6.90	5.28	58486	133995254	2291.00
6.60	5.01	62114	144628143	2328.00
6.30	4.73	63142	149132141	2361.00
6.00	4.46	66724	160648138	2407.00
5.70	4.18	67669	165024259	2438.00
5.40	3.93	75515	190461460	2522.00
5.10	3.65	76496	195654466	2557.00
4.80	3.39	81165	212408022	2616.00
4.50	3.10	82259	218517062	2656.00
4.20	2.87	92051	255366601	2774.00
3.90	2.58	92657	260788362	2814.00
3.60	2.33	98451	288770728	2933.00
3.30	2.07	103482	313138167	3026.00
3.00	1.79	104592	323164175	3089.00
2.70	1.56	115275	379508751	3292.00
2.40	1.31	121591	420228353	3456.00
2.10	1.02	121925	428945720	3518.00
1.80	0.77	127993	474548414	3707.00
1.50	0.54	140997	563687663	3997.00
1.20	0.30	147921	631565863	4269.00
0.90	0.09	161387	763318235	4729.00
0.60	0.00	167209	867479097	5187.00
0.30	0.00	203292	1179420043	5801.00

**Comment by taoliu** [comment]
@aneeshbio Sorry I am just catching up with the questions submitted here. pscore 4.8 means 10**-4.8 which is approximately 0.00001. Set it in command line as '-p 1e-5' or '-p 0.00001'.

**Comment by philippadoherty** [comment]
Closing this issue as stale, due to inactivity. Please feel free to re-open this with a comment.
