### ISSUE TITLE
possible --call-troughs option

### ISSUE THREAD

**Issue by dbrg77** [macs3-project/MACS#160]
Hi Tao,

Apologies if this is not the correct place to post a function request, but I'm not sure whether people are still visiting the macs google user group.

https://groups.google.com/forum/#!topic/macs-announcement/m6JXYMDeiRA

Aa suggested in the goole thread above, do you think you could implement a --call-troughs option, which is similar to --call-summits but to find the local minima? I think this will be very helpful for histone chip-seq, since regulatory elements tend to be located in the "dip" regions within the called peaks.

Thank you.

Regards,
Xi

**Comment by taoliu** [comment]
Hi Xu, thanks for the suggestion. I will consider this feature in the next release.

**Comment by jnasser3** [comment]
Hello, does MACS2 support trough finding?
