### ISSUE TITLE
Call differential binding events with replicates

### ISSUE THREAD

**Issue by atbest** [macs3-project/MACS#161]
Hi taoliu,

I have two H3K27Ac chip-seq biological duplicates for treated and untreated groups, but no input at all.
There are two different methods mentioned in wiki, [Run MACS2 combining replicates](https://github.com/taoliu/MACS/wiki/Build-Signal-Track#run-macs2-combining-replicates) simply merges two samples for each condition. [Call differential binding events](https://github.com/taoliu/MACS/wiki/Call-differential-binding-events) doesn't take replicates into consideration. Because the samples are biological repeats, I cannot compare treated-1 with untreated-1 and treated-2 with untreated-2. Could you please tell me what would be the best method for this situation?
Thanks you very much.

**Comment by kminie** [comment]
I also have same kind of experimental condition

**Comment by philippadoherty** [comment]
Closing this issue as stale, due to inactivity. Please feel free to re-open this with a comment.
