### ISSUE TITLE
How to normalize the output.bdg

### ISSUE THREAD

**Issue by JingxinGuo** [macs3-project/MACS#162]
Hi taoliu,
     Dose the macs2 normalize the values in pileup.bdg ? 
    Thanks you very much.

**Comment by dbrg77** [comment]
If it is from the "pileup" command:
    it is not.

If it is from the "callpeak" command:
    if you set "--SPMR" flag during the peakcalling:
        it is normalised to 1 million reads.
    else:
        it is not.

**Comment by philippadoherty** [comment]
Closing this issue as stale, due to inactivity. Please feel free to re-open this with a comment.
