### ISSUE TITLE
How to convert bedGraph file from macs2 to wig file for ceas analysis? 

### ISSUE THREAD

**Issue by Yongzhen1204** [macs3-project/MACS#164]
Hi Liu,
  
      macs1.4 can build the wig file for ceas analysis while macs2 not, so how to convert bdg file from macs2 to wig file for ceas?

       Thank you!

Yongzhen  CAU

**Comment by philippadoherty** [comment]
Closing this issue as stale, due to inactivity. Please feel free to re-open this with a comment.
