### ISSUE TITLE
MACS2 default q-value cutoff

### ISSUE THREAD

**Issue by komalsrathi** [macs3-project/MACS#165]
I am using MACS2 version: `macs2 2.1.0.20150731`. The documentation on macs2 --help says that the default q-value cut off is 0.05. But your documentation page here says it is 0.01. Can you clarify which is correct?

**Comment by taoliu** [comment]
Should be 0.05. I will fix the document soon.

Tao

**Comment by philippadoherty** [comment]
Closing this issue as stale, due to inactivity. Please feel free to re-open this with a comment.
