### ISSUE TITLE
Negative peak candidates from MACS2

### ISSUE THREAD

**Issue by Anupriya014** [macs3-project/MACS#167]
Hello @taoliu !

Recently, I've done a chip-seq project. In that I've to treat one of the sample as control that's not IgG/Input. So I wanted to get peaks that were both over expressed & under expressed in sample as compared to this control. In other words, I wanted 'negative peaks' also. Below is the command for it :

macs2 callpeak -f BAMPE -t @chip1 -c @control1 -g $org -n $input_path/results1/macs2/G'$itr'_C1_T1_broad_peaks -B --mfold -60 60 --broad --broad-cutoff 0.1 --bw 300 --buffer-size 100000 --qvalue 0.05 --slocal 1000 --llocal 10000 --cutoff-analysis --fe-cutoff 1.0

As written in README file :
'-n/--name
The name string of the experiment. MACS will use this string NAME to create output files like 'NAME_peaks.xls', 'NAME_negative_peaks.xls'..'  MACS2 will give me negative_peaks.xls. But it didn't gave any negative peaks for me. 

I saw in 'PeakDetect.pyx' this :

    #     self.info("#3 diag: call negative peak candidates")
    #     negative_peak_candidates = self.__call_peaks_from_trackI (self.control)

Is it that MACS2 doesn't call for negative peaks whereas MACS1.4 does? 
If so, do I need to swap control & sample manually & then run MACS2 for negative peaks?

Please help me out.

Thank you in advance!

-Anupriya Verma

**Comment by taoliu** [comment]
MACS2 won't call 'negative peaks'. The FDR is calculated through Benjamin-Horchberg process ( adjustment based on the distribution of p-values). To call negative peaks, swap the ChIP and control manually such as '-t control.bam -c chip.bam'

**Comment by philippadoherty** [comment]
Closing this issue as stale, due to inactivity. Please feel free to re-open this with a comment.
