### ISSUE TITLE
"advanced MACS2 subcommands" wiki tutorial incorrect parameter

### ISSUE THREAD

**Issue by passdan** [macs3-project/MACS#172]
The **"Combine and generate the maximum background noise"** section has the following commands for building background track:

> 
> Take the maximum between slocal (1k) and llocal (10k) background:
> `macs2 bdgcmp -m max -t 1k_bg_norm.bdg -c 10k_bg_norm.bdg -o 1k_10k_bg_norm.bdg
> `
> Then, take the maximum then by comparing with d background:
> `macs2 bdgcmp -m max -t 1k_10k_bg_norm.bdg -c d_bg.bdg -o d_1k_10k_bg_norm.bdg
> `
> 

However `bdgcmp -m` doesnt have the 'max' option. 

This command is designed to be finding the maximum noise of the regions, so is it supposed to be cmbreps rather than bdgcmp? In which case the line would be:

`macs2 cmbreps -m max -i 1k_bg.bdg 10k_bg.bdg -o 1k_10k_bg_norm.bdg
`
Additionally, the next command:

> Finally, combine with the genome wide background using bdgopt subcommand
> `macs2 bdgopt -i d_1k_10k_bg_norm.bdg -m max -p .0188023 -o local_bias_raw.bdg`

doesnt have a 'max' option, and should be multiply I think.

Is this correct?

https://github.com/taoliu/MACS/wiki/Advanced:-Call-peaks-using-MACS2-subcommands#combine-and-generate-the-maximum-background-noise

**Comment by philippadoherty** [comment]
Closing this issue as stale, due to inactivity. Please feel free to re-open this with a comment.
