### ISSUE TITLE
Is there any way I can get peaks' pvalues or qvalues when I use bdgpeakcall?

### ISSUE THREAD

**Issue by ChengfeiYan** [macs3-project/MACS#178]
Hi,

I am trying to run MACS2 step by step based on MACS2' advanced tutorial.
However, I just found that the pvalue and qvalue columns in the final bed file of peaks generated by bdgpeakcall are missing.

Is there anyway I can get these values ?
If not, is there any other way I can use to rank these peaks? (e.g. integer score for display?)

Your help will be greatly appreciated!
Chengfei Yan

**Comment by philippadoherty** [comment]
Closing this issue as stale, due to inactivity. Please feel free to re-open this with a comment.
