### ISSUE TITLE
question about wigCorrelation

### ISSUE THREAD

**Issue by KeyingLu** [macs3-project/MACS#181]
I want to know the correlation of several biological replicates that are produced by chip-seq. I have used wigCorrelation to get correlation, but I don't know what the correlation is good enough.

**Comment by taoliu** [comment]
Check ChiLin paper :) 

https://bmcbioinformatics.biomedcentral.com/articles/10.1186/s12859-016-1274-4

**Comment by philippadoherty** [comment]
Closing this issue as stale, due to inactivity. Please feel free to re-open this with a comment.
