### ISSUE TITLE
bdgdiff comparison issue

### ISSUE THREAD

**Issue by shengyongniu** [macs3-project/MACS#185]
Hi there,

I'm trying to use MACS2 bdgdiff for my ATAC-seq differential peaks analysis. I want to compare the differential expression between T2D (Type 2 Diabetes) and ND(Non-diabetes, control) with the same cell type. For example, compare T2D_Bcell with ND_Bcell. 
My question is, in the arguments of bdgdiff, what should I put for the arguments for the analysis?
How about:
Condition1: T2D_Bcell
Control1: ND_Bcell
Condition2: ND_Bcell
Control2: ND_Bcell  ?
I want to compare one sample (T2D) with one control (ND). What should I put for condition and control arguments?

Simon

**Comment by taoliu** [comment]
Control1 and Control2 should be T2D control background and ND background correspondingly. After you run 'callpeaks -B -f BAMPE -t xxx.bam' on T2D and ND ATAC-Seq separately, you would get a '_treat_pileup.bdg' and '_control_lambda.bdg' for each condition. So the setting is:
Condition1: T2D_Bcell_treat_pileup.bdg
Control1: T2D_Bcell_control_lambda.bdg
Condition2: ND_Bcell_treat_pileup.bdg
Control2: ND_Bcell_control_lambda.bdg

**Comment by philippadoherty** [comment]
Closing this issue as stale, due to inactivity. Please feel free to re-open this with a comment.
