### ISSUE TITLE
Cutoff analysis results

### ISSUE THREAD

**Issue by kernco** [macs3-project/MACS#191]
I'm confused about the output in the cutoff_analysis.txt file generated when the --cutoff-analysis argument is used. Why are the pscore and qscore values ranging from ~10 to 0? Are these -log(pvalue) and -log(qvalue)? Also when using the macs2 command you can only specify a p-value OR a q-value, but the cutoff analysis shows peak calling results for pairs of p-value and q-values. I'm not sure how to interpret that.

**Comment by flyingicedragon** [comment]
I think they are -log(pvalue) and -log(qvalue) but I am not sure. Q-values are caculated from p-values.

> Q-values are the name given to the adjusted p-values found using an optimised FDR approach. The FDR approach is optimised by using characteristics of the p-value distribution to produce a list of q-values.

**Comment by philippadoherty** [comment]
Closing this issue as stale, due to inactivity. Please feel free to re-open this with a comment.
