### ISSUE TITLE
Is read coverage normalised to RPM or RPGC?

### ISSUE THREAD

**Issue by jma1991** [macs3-project/MACS#193]
When running `macs2 callpeak` with the  flags `-g GSIZE -B --SPMR` are the bedGraphs files produced normalised to reads per million (RPM), or is the effective genome size included in the calculation (RPGC), similar to the normalisation used in the [deepTools command bamCoverage](https://deeptools.readthedocs.io/en/latest/content/tools/bamCoverage.html)?

**Comment by chiefcat** [comment]
Hi Jma, I want to ask this question too. Have you gotten any idea so far? Is there anyway to produce RPGC normalized bedGraphs by MACS2? Thanks!

**Comment by philippadoherty** [comment]
Closing this issue as stale, due to inactivity. Please feel free to re-open this with a comment.
