### ISSUE TITLE
Feature request - allow refinepeak to use peak interval instead of window

### ISSUE THREAD

**Issue by jma1991** [macs3-project/MACS#194]
I have peak intervals generated from intersecting peaks from multiple studies measuring the same factor. When I intersect these peaks I lose all information about peak summits. I would like to use the refinepeak command to identify the summits for these new peaks. To do this I tried setting the window size to zero because I only want to look for summits within the pre-defined peak intervals. However the search space is then limited to just the first base pair of the peak interval (because it assumes you are passing in a single base-pair summit interval). It would be very helpful if the refinepeak command would take the full peak-interval as the search space.

**Comment by philippadoherty** [comment]
Closing this issue as stale, due to inactivity. Please feel free to re-open this with a comment.
