### ISSUE TITLE
Questions about bdgdiff output

### ISSUE THREAD

**Issue by olechnwin** [macs3-project/MACS#199]
Hi,
Can you please explain how differential regions are called?
The differential region seems to have overlap with individual peak called on cond1 and cond2?
For example these are the peaks called on cond1, cond2 and enriched in cond2
peak on cond1. chr1:13,203-14,976
peak on cond2. chr1:11,900-16,152
enrich in cond2. chr1:12,432-15,783
The enrich region in cond2 overlap with peaks in both cond1 and cond2? How is this region determined?
Also, is there a way to tell the intensity of peak increases/decreases ?

**Comment by philippadoherty** [comment]
Closing this issue as stale, due to inactivity. Please feel free to re-open this with a comment.
