### ISSUE TITLE
Bed file to enrichment scores 

### ISSUE THREAD

**Issue by girdhar3** [macs3-project/MACS#204]
I have a consensus peak bed file for which I have to quantify the enrichment score of bam files against their respective control file. What is the best way in macs2 software to get enrichment scores of given bed file?

Also, is the col. 7 in narrowpeak file is the enrichment score for a given peak regions averaged over the width of the peak?

**Comment by philippadoherty** [comment]
Closing this issue as stale, due to inactivity. Please feel free to re-open this with a comment.
