### ISSUE TITLE
MACS2 Stalling

### ISSUE THREAD

**Issue by sklasfeld** [macs3-project/MACS#216]
For some of my samples, MACS2 stalls when I remove the duplicates (either by --keep-dup 1 or when I manually remove the duplicates).  There is no error that is output, but the analysis is stalled at for example:
"INFO  @ Tue, 10 Oct 2017 11:02:53: #3 Call peaks... 
INFO  @ Tue, 10 Oct 2017 11:02:53: #3 Pre-compute pvalue-qvalue table... "

**Comment by philippadoherty** [comment]
Closing this issue as stale, due to inactivity. Please feel free to re-open this with a comment.
