### ISSUE TITLE
OverflowError: value too large to convert to int

### ISSUE THREAD

**Issue by georgeg9** [macs3-project/MACS#24]
Whenever I am running macs for that bam file ( with only unique mapped reads) it get stuck at "36000000" for few hours and then I get this error.

INFO  @ Tue, 08 Oct 2013 11:53:22: #1 read tag files... 
INFO  @ Tue, 08 Oct 2013 11:53:22: #1 read treatment tags... 
INFO  @ Tue, 08 Oct 2013 11:53:28:  1000000 
INFO  @ Tue, 08 Oct 2013 11:53:33:  2000000 
INFO  @ Tue, 08 Oct 2013 11:53:38:  3000000 
INFO  @ Tue, 08 Oct 2013 11:53:44:  4000000 
INFO  @ Tue, 08 Oct 2013 11:53:49:  5000000 
INFO  @ Tue, 08 Oct 2013 11:53:55:  6000000 
INFO  @ Tue, 08 Oct 2013 11:54:00:  7000000 
INFO  @ Tue, 08 Oct 2013 11:54:05:  8000000 
INFO  @ Tue, 08 Oct 2013 11:54:11:  9000000 
INFO  @ Tue, 08 Oct 2013 11:54:16:  10000000 
INFO  @ Tue, 08 Oct 2013 11:54:21:  11000000 
INFO  @ Tue, 08 Oct 2013 11:54:27:  12000000 
INFO  @ Tue, 08 Oct 2013 11:54:32:  13000000 
INFO  @ Tue, 08 Oct 2013 11:54:37:  14000000 
INFO  @ Tue, 08 Oct 2013 11:54:43:  15000000 
INFO  @ Tue, 08 Oct 2013 11:54:48:  16000000 
INFO  @ Tue, 08 Oct 2013 11:54:53:  17000000 
INFO  @ Tue, 08 Oct 2013 11:54:59:  18000000 
INFO  @ Tue, 08 Oct 2013 11:55:04:  19000000 
INFO  @ Tue, 08 Oct 2013 11:55:09:  20000000 
INFO  @ Tue, 08 Oct 2013 11:55:14:  21000000 
INFO  @ Tue, 08 Oct 2013 11:55:20:  22000000 
INFO  @ Tue, 08 Oct 2013 11:55:25:  23000000 
INFO  @ Tue, 08 Oct 2013 11:55:30:  24000000 
INFO  @ Tue, 08 Oct 2013 11:55:36:  25000000 
INFO  @ Tue, 08 Oct 2013 11:55:41:  26000000 
INFO  @ Tue, 08 Oct 2013 11:55:46:  27000000 
INFO  @ Tue, 08 Oct 2013 11:55:51:  28000000 
INFO  @ Tue, 08 Oct 2013 11:55:57:  29000000 
INFO  @ Tue, 08 Oct 2013 11:56:02:  30000000 
INFO  @ Tue, 08 Oct 2013 11:56:07:  31000000 
INFO  @ Tue, 08 Oct 2013 11:56:13:  32000000 
INFO  @ Tue, 08 Oct 2013 11:56:18:  33000000 
INFO  @ Tue, 08 Oct 2013 11:56:23:  34000000 
INFO  @ Tue, 08 Oct 2013 11:56:29:  35000000 
INFO  @ Tue, 08 Oct 2013 11:56:34:  36000000 
Traceback (most recent call last):
  File "/usr/bin/macs2", line 514, in <module>
    main()
  File "/usr/bin/macs2", line 45, in main
    run( args )
  File "/usr/lib64/python2.7/site-packages/MACS2/callpeak.py", line 69, in run
    else:       (treat, control) = load_tag_files_options  (options)
  File "/usr/lib64/python2.7/site-packages/MACS2/callpeak.py", line 379, in load_tag_files_options
    treat = tp.build_fwtrack()
  File "cParser.pyx", line 824, in MACS2.IO.cParser.BAMParser.build_fwtrack (MACS2/IO/cParser.c:10311)
  File "cParser.pyx", line 828, in MACS2.IO.cParser.BAMParser.build_fwtrack (MACS2/IO/cParser.c:10262)
  File "cParser.pyx", line 891, in MACS2.IO.cParser.BAMParser.__build_fwtrack_wo_pysam (MACS2/IO/cParser.c:11246)
  File "cParser.pyx", line 1015, in MACS2.IO.cParser.BAMParser.__fw_binary_parse (MACS2/IO/cParser.c:13208)
OverflowError: value too large to convert to int

**Comment by andreakcl89** [comment]
Error with macs2 version macs2 2.1.0.20150731, on OSX El Capitan:

INFO  @ Wed, 11 Nov 2015 15:29:57:
# Command line: callpeak -t sox32.bed -g 1.3e-9 -p 0.001 --bw=300 -B -f BED -n test_sox32
# ARGUMENTS LIST:
# name = test_sox32
# format = BED
# ChIP-seq file = ['sox32.bed']
# control file = None
# effective genome size = 1.30e-09
# band width = 300
# model fold = [5, 50]
# pvalue cutoff = 1.00e-03
# qvalue will not be calculated and reported as -1 in the final output.
# Larger dataset will be scaled towards smaller dataset.
# Range for calculating regional lambda is: 10000 bps
# Broad region calling is off

INFO  @ Wed, 11 Nov 2015 15:29:57: #1 read tag files...
INFO  @ Wed, 11 Nov 2015 15:29:57: #1 read treatment tags...
INFO  @ Wed, 11 Nov 2015 15:29:58:  1000000
INFO  @ Wed, 11 Nov 2015 15:30:00:  2000000
INFO  @ Wed, 11 Nov 2015 15:30:01:  3000000
INFO  @ Wed, 11 Nov 2015 15:30:02:  4000000
INFO  @ Wed, 11 Nov 2015 15:30:03:  5000000
INFO  @ Wed, 11 Nov 2015 15:30:04:  6000000
INFO  @ Wed, 11 Nov 2015 15:30:05:  7000000
INFO  @ Wed, 11 Nov 2015 15:30:06:  8000000
INFO  @ Wed, 11 Nov 2015 15:30:07:  9000000
INFO  @ Wed, 11 Nov 2015 15:30:08:  10000000
INFO  @ Wed, 11 Nov 2015 15:30:09: #1 tag size is determined as 73 bps
INFO  @ Wed, 11 Nov 2015 15:30:09: #1 tag size = 73
INFO  @ Wed, 11 Nov 2015 15:30:09: #1  total tags in treatment: 10878224
INFO  @ Wed, 11 Nov 2015 15:30:09: #1 user defined the maximum tags...
INFO  @ Wed, 11 Nov 2015 15:30:09: #1 filter out redundant tags at the same location and the same strand by allowing at most 1 tag(s)
INFO  @ Wed, 11 Nov 2015 15:30:10: #1  tags after filtering in treatment: 6261074
INFO  @ Wed, 11 Nov 2015 15:30:10: #1  Redundant rate of treatment: 0.42
INFO  @ Wed, 11 Nov 2015 15:30:10: #1 finished!
INFO  @ Wed, 11 Nov 2015 15:30:10: #2 Build Peak Model...
Traceback (most recent call last):
  File "/Users/andrea/Programs_NGS/MACS/bin/macs2", line 614, in <module>
    main()
  File "/Users/andrea/Programs_NGS/MACS/bin/macs2", line 56, in main
    run( args )
  File "/usr/local/lib/python2.7/site-packages/MACS2/callpeak_cmd.py", line 175, in run
    opt = options
  File "MACS2/PeakModel.pyx", line 108, in MACS2.PeakModel.PeakModel.__init__ (MACS2/PeakModel.c:2385)
  File "MACS2/PeakModel.pyx", line 123, in MACS2.PeakModel.PeakModel.build (MACS2/PeakModel.c:2521)
OverflowError: value too large to convert to int
