### ISSUE TITLE
Why are input/control reads counted twice in PE mode?

### ISSUE THREAD

**Issue by daniel-wells** [macs3-project/MACS#271]
At first I thought MACS2 was scaling the wrong sample, the control sample was being scaled but based on the stdout it seemed to be the smaller dataset:
```
total fragments in treatment: 39844232
total fragments in control: 22946943
```

But I see in the source code that for PE mode the control/input fragments are counted twice meaning the control size is actually 45893886 - what is the reasoning for this?

Thanks!
Daniel

**Comment by philippadoherty** [comment]
Closing this issue as stale, due to inactivity. Please feel free to re-open this with a comment.
