### ISSUE TITLE
Would it be possible to include a NAME_summits.bed file in the output of bdgpeakcall?

### ISSUE THREAD

**Issue by CesarArenas-Mena** [macs3-project/MACS#276]
I get the peak call file, but not summits.
Thanks,
Cesar

**$ macs2 bdgpeakcall -i 12_hours_dedup_QC_end_plus5.bedGraph -c 5 -l 1 -o 12hl1c5_bdg
$ head 12hl1c5_bdg
track type=narrowPeak name="12hl1c5_bdg" description="12hl1c5_bdg" nextItemButton=on
Scaffold1       6650    6656    12hl1c5_bdg_narrowPeak1 50      .       0.00000 0.00000 0.00000 0
Scaffold1       6806    6849    12hl1c5_bdg_narrowPeak2 50      .       0.00000 0.00000 0.00000 21
Scaffold1       8514    8569    12hl1c5_bdg_narrowPeak3 60      .       0.00000 0.00000 0.00000 27
Scaffold1       9238    9250    12hl1c5_bdg_narrowPeak4 50      .       0.00000 0.00000 0.00000 6
Scaffold1       9420    9452    12hl1c5_bdg_narrowPeak5 70      .       0.00000 0.00000 0.00000 16**

**Comment by philippadoherty** [comment]
Closing this issue as stale, due to inactivity. Please feel free to re-open this with a comment.
