### ISSUE TITLE
Feat: HMMRATAC integration

### ISSUE THREAD

**Issue by taoliu** [macs3-project/MACS#320]
HMMRATAC (https://github.com/LiuLabUB/HMMRATAC) is a dedicated peak caller for ATAC-seq data. It is written in JAVA, and it has some shared ideas with MACS2. It can be rewritten in Python3 and be integrated into MACS as a subcommand while dealing with ATAC-seq data.

**Describe the solution you'd like**

1. JAVA -> Python3 translation
2. Share MACS components
3. Design unit tests

**Additional context**
Some difficulties: HMMRATAC contains machine learning components such as EM algorithm, and Hidden Markov Models. We may need to introduce more dependencies including scikit-learn, hmmlearn and matplotlib.

**Comment by hyjforesight** [comment]
Hello @taoliu,
just want to check whether it is available to call HMMRATAC in MACS3 now? I didn't find this sub function in MACS3.
![image](https://user-images.githubusercontent.com/75048821/161195357-45534e23-f331-4309-bac6-a4a9cd991d14.png)
Thanks!
Best,
YJ

**Comment by taoliu** [comment]
@hyjforesight  We are developing it in this branch: https://github.com/macs3-project/MACS/tree/feat/macs3/hmmratac Almost there :)
