### ISSUE TITLE
MACS2 vs MACS3

### ISSUE THREAD

**Issue by YogiOnBioinformatics** [macs3-project/MACS#403]
What exactly is the difference between MACS2 and this MACS3 project? 

What specifically is trying to be aimed by MACS3? 

Could not find a clear explanation of this searching through the "Issues".

**Comment by taoliu** [comment]
@YogiOnBioinformatics It's a work in progress. I am organizing all features towards MACS3 in this page: https://github.com/macs3-project/MACS/projects/1

**Comment by YogiOnBioinformatics** [comment]
Alright thanks for showing me that. 

I guess then the main motivator is speed???? 

What other motivators do you have for MACS3 to be better than MACS2?

**Comment by taoliu** [comment]
@YogiOnBioinformatics We will start to implement more functions mentioned in the 'to do' list of that project page. Here are the major things: 1. optimizing the speed; 2. a better (sc/bulk) ATAC-seq peak calling module; 3. a module to directly infer the DNA sequence and variants (while comparing with reference sequence) at the peak from sequencing data; 4. a new differential peak calling module; 5. detailed documentation. And so on.

**Comment by YogiOnBioinformatics** [comment]
That is so awesome!!!! 

I can't wait for all these changes to happen. 
I really appreciate you doing this work 🙂 ! 

Is there an idea in mind for when you think MACS3 will be fully finished (i.e. the first official release) with the above changes?

**Comment by YogiOnBioinformatics** [comment]
sorry to bother. 
just wanted to follow up on this.

**Comment by taoliu** [comment]
Hi @YogiOnBioinformatics, we are getting support from CZI to finish this project in a year (https://chanzuckerberg.com/eoss/proposals/macs3-a-versatile-peak-caller-for-gene-regulation-studies/). We will keep the pace to release major updates each quarter. I'm building up the team currently and will start the work soon.

**Comment by YogiOnBioinformatics** [comment]
Amazing! 

Great to hear and best of luck! 
The Bioinformatics community is eager and willing to help.

**Comment by taoliu** [comment]
@YogiOnBioinformatics Definitely welcome any help from our wonderful community, as in the past 12 years!
