### ISSUE TITLE
Q: Why don't model.r files work?

### ISSUE THREAD

**Issue by c5creative** [macs3-project/MACS#417]
**RESOLVED!!!**

**Sorry, after re-reading various docs, I see my mistake. I needed to run `Rscript model.r` at the CLI. I'll leave this here for future reference.**

----

Thank you for reading and feedback!

**Use case**
MACS2 works fine but I've never been able to get the generated `model.r` files to run.

**Describe the problem**
The MACS2-generated R file contains several vectors:

```
p <- c(0.036822804229564896,0.042945149993034726,0.04844638821528297, ...)
m <- c(0.04235406205004406,0.0489205832981129,0.055904974080149765, ...)
etc...
```
Upon executing loading of vector `p`, the console awaits more content (it shows the `+` sign and not the `>` sign). If I provide the console an additional `)`, it appears to finish loading the vector, HOWEVER it shows a length of 264 vector elements, far short of what's trying to load.. This is in R 3.6.3.

**Describe the solution you tried**
I was running an older version of MACS2 and upgraded to 2.2.7.1 (via bioconda) and the issue remains. I also looked through the `p` vector and nothing jumped out at me as being wrong within it. I'm thinking it's something silly on my part but have run out of ideas. 

**Additional context**
I have provided the entire R file at https://pastebin.com/aCtwGWPM.

**Comment by taoliu** [comment]
Thanks for the feedback :)

Some history: many years ago, in the old version MACS (perhaps version 1), we let MACS invoke R command line to process the r script file to generate a PDF. But later, since I want to remove the unnecessary dependencies, I changed the design and  only keep the unprocessed r script as the output.
