### ISSUE TITLE
Bug: Installation error on Windows using pip install macs2

### ISSUE THREAD

**Issue by philyang07** [macs3-project/MACS#441]
**Describe the bug**
When using `pip install macs2`, when building the wheel, an error `LINK : fatal error LNK1181: cannot open input file 'm.lib'
  error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\Tools\\MSVC\\14.21.27702\\bin\\HostX86\\x64\\link.exe' failed with exit status 1181` occurs.

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/48355111/105127077-09b47c80-5b1b-11eb-86ce-f017351cd31b.png)

**System
 - OS: Windows 10
 - Python version: 3.8.6
 - Numpy version: 1.20
 - MACS version: 2.2.7.1

**Additional context**
I have also tried downloading and using the setup script to install MACS2. There is a line in the script where there is an "m". 
![image](https://user-images.githubusercontent.com/48355111/105127190-4d0eeb00-5b1b-11eb-8a46-1c4c521c4be0.png)
I have tried removing it and changing it but it still fails to install.
![image](https://user-images.githubusercontent.com/48355111/105127293-8b0c0f00-5b1b-11eb-8a76-ae1d48c2a7ec.png)

**Comment by taoliu** [comment]
`m` is the  C math library under Linux. I recommend using MACS under either Linux or MacOSX. Windows is not supported.

**Comment by bgorissen** [comment]
I've been able to build macs2 on Windows with MVCC. Just download the source code from Github, open setup.py and change `["m"]` into `[]` and `-Ofast` into `/Ox`, then open `Pileup.pyx` and change `compare(const void * a, const void * b)` into `compare(const char * a, const char * b)`, and finally run `python setup.py install`. Then you can run macs2 via `python -c "__import__('pkg_resources').run_script('MACS2', 'macs2')"`.
