### ISSUE TITLE
Should Debian ship MACS 3.0.0 alpha 6 in the next Debian stable release?

### ISSUE THREAD

**Issue by mr-c** [macs3-project/MACS#447]
Hello,

The window for updates to Debian packages for Debian "Bullseye" is closing soon. Currently we have [MACS 2.2.7.1](https://packages.debian.org/source/testing/macs). Should we instead be shipping the latest MACS 3.0.0 alpha, or is that still too soon?

**Comment by taoliu** [comment]
@mr-c Still too soon. I am working on adding more features to MACS3. Please still have MACS 2.2.7.1. Thanks for asking :)

**Comment by mr-c** [comment]
Thanks for the quick answer; best wishes!
