### ISSUE TITLE
Bug: negative values produced for offset column

### ISSUE THREAD

**Issue by blawney** [macs3-project/MACS#450]
I've tried several versions (most recently 2.2.7.1 containerized here: https://hub.docker.com/r/fooliu/macs2) and I keep getting a recurring issue where the final column (10th col, peak offset) receives negative values-- contigs over 1e9bp seems to be the threshold that breaks a lot of the tools we're used to with human/mouse. This is naturally throwing off the remainder of our process (loosely based on the ENCODE pipeline).

As is clear from the start sites, this is related to this organism (axolotl) having very large contigs. We've already had to use different BAM indexing, etc. to get suitable tag files (and updated bedtools versions using 64-bit ints). 

I suppose the work-around would be to split and subsequently merge the contigs to get them under 1e9 bp. But maybe we're missing a flag or something that would allow us to run MACS2 without resorting to that...?

Thanks! Hopefully I have not missed anything relevant or made any glaring mistakes!

Command (based on older ENCODE process) was as follows. All commands run inside of the aforementioned Docker image.
```
root@64443225403a:/work# macs2 --version
macs2 2.2.7.1
```

```
macs2 callpeak 
    -t pulldown.tagAlign 
    -c input.tagAlign
     -f BED 
     -n zzz 
     -p 0.01 
     --nomodel 
     --shift 0 
     --extsize 200 
     --keep-dup all 
     -B 
     --SPMR
```
Example output:
```
chr10p	1073719728	1073719928	zzz_peak_49839	24	.	2.31041	2.44992	0.500814	24
chr10p	1073722889	1073723176	zzz_peak_49840	34	.	3.13098	3.41397	0.759108	111
chr10p	1073732609	1073732848	zzz_peak_49841	44	.	3.68143	4.43782	0.959737	148
chr10p	1073774034	1073774389	zzz_peak_49842	35	.	3.08054	3.58377	0.805273	-2147483492
chr10p	1073821756	1073821974	zzz_peak_49843	41	.	3.52644	4.12448	0.89786	-2147483594
chr10p	1073822267	1073822467	zzz_peak_49844	20	.	2.11586	2.04971	0.410871	-2147483585
chr10p	1073825075	1073825285	zzz_peak_49845	32	.	2.94515	3.28755	0.732502	-2147483449
chr10p	1073827168	1073827389	zzz_peak_49846	30	.	2.82115	3.04023	0.612908	-2147483509
``` 

I can provide the input tag files if necessary.

**Comment by taoliu** [comment]
Interesting. @blawney Could you share with me your tagAlign file? Definitely an overflow issue. The peak boundaries are correct but the summit location was calculated incorrectly.

**Comment by blawney** [comment]
I truncated the files and dropped them into a google bucket (public access). ~8MB each. On my end, the error is still produced with these smaller files.

https://storage.googleapis.com/macs2-450-tagalign-files/input_truncated.tagAlign
https://storage.googleapis.com/macs2-450-tagalign-files/pulldown_truncated.tagAlign

**Comment by taoliu** [comment]
@blawney Thanks for sharing! I can reproduce the error on my computer as well. I will look into it... Stay tuned.

**Comment by taoliu** [comment]
@blawney The problem is that I used int32 to store the coordinates in chromosomes. int32 has a range between (approx) -2G to 2G. Then when I calculated the summit location, the start and end positions with the maximum value within the peak will be added then divided by 2, in order to get the mid point of the maximum region.  In your example, the sum of start and end just passed the limit of 2G (2,147,483,648) then caused an overflow. 

Solution: I will fix it in the next MACS3 alpha release and perhaps patch MACS2 branch to use uint32 instead of int32 for storing the coordinates and in this way, maximum 2G per chromosome can be supported. I also have to review the usage of int32 across all source codes though.

But on your end,  there is a possible temporary fix. Since it's just an overflow and the actual number ( the relative summit location in peak) won't be a huge number, you can just add 2147483648 to the negative value. For example:
```
chr10p	1073774034	1073774389	zzz_peak_49842	35	.	3.08054	3.58377	0.805273	-2147483492
chr10p	1073821756	1073821974	zzz_peak_49843	41	.	3.52644	4.12448	0.89786	-2147483594
chr10p	1073822267	1073822467	zzz_peak_49844	20	.	2.11586	2.04971	0.410871	-2147483585
chr10p	1073825075	1073825285	zzz_peak_49845	32	.	2.94515	3.28755	0.732502	-2147483449
chr10p	1073827168	1073827389	zzz_peak_49846	30	.	2.82115	3.04023	0.612908	-2147483509
```
Becomes:
```
chr10p	1073774034	1073774389	zzz_peak_49842	35	.	3.08054	3.58377	0.805273	156
chr10p	1073821756	1073821974	zzz_peak_49843	41	.	3.52644	4.12448	0.89786	54
chr10p	1073822267	1073822467	zzz_peak_49844	20	.	2.11586	2.04971	0.410871	63
chr10p	1073825075	1073825285	zzz_peak_49845	32	.	2.94515	3.28755	0.732502	199
chr10p	1073827168	1073827389	zzz_peak_49846	30	.	2.82115	3.04023	0.612908	139
```

**Comment by blawney** [comment]
Thanks! I can easily implement the manual fix. The fact that the threshold for the errors wasn't at 2^31 was throwing me off...but the explanation about the sum makes perfect sense.

**Comment by blawney** [comment]
Sorry, realized I probably should let you close this, but I can't undo my close...
