### ISSUE TITLE
ZeroDivisionError: integer division or modulo by zero (with /MACS1/IO/Parser.py)

### ISSUE THREAD

**Issue by jcness216** [macs3-project/MACS#458]
"File "/Library/Python/2.7/site-packages/MACS1/IO/Parser.py", line 655, in tsize     return int(s/n) ZeroDivisionError: integer division or modulo by zero"

I have my .sam files ready to go after being SRR files were processed by bowtie1.1.1 --was having issues with newer bowtie versions (the data is not sorted)

When processing using MACS, I am encountering an error with Parser.py (error above)

In terms of troubleshooting, I am at a bit of a loss. If anyone has encountered this error before, I would appreciate it.
Maybe my .sam file is not correct?

**Comment by taoliu** [comment]
@jcness216  I suggest you to install the most recent version of MACS ( or at least v2.2.7.1 ) to see if the error is still there. According to the path `/Library/Python/2.7/site-packages/MACS1/IO/Parser.py`, you are using Python version 2 which officially retired a year ago. 

Another possible cause is that MACS can't find any 'records' in the SAM file. I am not sure if the SAM file is in correct format. But you can try to convert it into binary format with 'samtools' then use 'samtools flagstat' to see if the summary of the alignment is correct. In this way, you can make sure the 'bam' file is valid. Then use that BAM file as input for MACS.

**Comment by jcness216** [comment]
Thank you for your quick response @taoliu . After searching the internet, it looks like I somehow need to override the -s tagsize because the program isn’t finding it itself. I probably should try MACS2 as it seems like this version doesn’t need that ...
