### ISSUE TITLE
macs3 "mean fragment size is determined as 0.0 bp from treatment"

### ISSUE THREAD

**Issue by Delta-43** [macs3-project/MACS#465]
I'm trying to call peaks from encode data, but it estimates fragment sizes as 0, which is impossible and then it throws this error `ZeroDivisionError: float division`

**Comment by taoliu** [comment]
@Delta-43 It's possible that MACS can't find any 'valid' reads from the alignment files. Could you share me some information regarding the alignment files you used for MACS and post the entire message from MACS?

**Comment by Delta-43** [comment]
Sorry, it was my bad I was using BEDPE mode whereas the file actually had single ended reads. Thanks anyway.
