### ISSUE TITLE
Q: Reproducibility of MACS3 on the same sample

### ISSUE THREAD

**Issue by yjqiu** [macs3-project/MACS#503]
I tried to run MACS3 on the same input bam file and get slightly different peak lists. The difference is pretty minor but I am curious if MACS3 is designed to reproduce the same output every time. Or there is some randomness and the peaks may be slightly different every time. 

I tried to search issues or online but cannot find a clear answer. Most people seem to care more about reprowducilty between biological replicates.

**Comment by taoliu** [comment]
@yjqiu The only place, where a random generator is involved, is in the 'sampling' step.  There shouldn't be randomness elsewhere. Could you describe your situation in detail? Such as the command and parameters you used?

**Comment by yjqiu** [comment]
Hi @taoliu Thanks for the explanation! I just replied that the input bam files are slightly different and MACS3 in fact generates the same output. Sorry for the trouble.
