### ISSUE TITLE
bedGraphToBigWig: error while loading shared libraries: libssl.so.1.0.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by hyjforesight** [macs3-project/MACS#505]
**Describe the bug**
Hello MACS3,
I'm trying to convert bedGraph to bigWig (which is generated by MACS3). I followed your tutorial here (https://gist.github.com/taoliu/2469050).
However, I met errors `bedGraphToBigWig: error while loading shared libraries: libssl.so.1.0.0: cannot open shared object file: No such file or directory`.
I tried below coding, but openssl is upgraded to v1.1.1f and error was not solved. I found that Unbuntu20.04 has droped the installation of openssl v1.0.0.
```python
sudo apt-get update -y
sudo apt-get install -y libssl-dev
sudo ln -s libssl.so.1.1.1f libssl.so.1.0.0
sudo ln -s libcrypto.so.1.1.1f libcrypto.so.1.0.0
```
Also tried all solutions here (https://askubuntu.com/questions/1261614/ubuntu-20-04-libssl-so-1-0-0-cannot-open-shared-object-file-no-such-file-or-d). Didn't work.

Appreciate it if you could help me with this issue.
Thanks!
Best,
YJ

**To Reproduce**
```python
conda install -c bioconda ucsc-bedclip
conda install -c bioconda ucsc-bedgraphtobigwig
bedtools slop -i /home/hyjforesight/MACS3_outputs/Cracd_KO1_treat_pileup.bdg -g /home/hyjforesight/mm10_chromInfo.txt -b 0 | bedClip stdin /home/hyjforesight/mm10_chromInfo.txt /home/hyjforesight/bigWig/Cracd_KO1_treat_pileup_clip.bdg    # clip bedGraph generated by MACS2
LC_ALL=C sort -k1,1 -k2,2n /home/hyjforesight/bigWig/Cracd_KO1_treat_pileup_clip.bdg > /home/hyjforesight/bigWig/Cracd_KO1_treat_pileup_clip_sorted.bdg    # sort
bedGraphToBigWig /home/hyjforesight/bigWig/Cracd_KO1_treat_pileup_clip_sorted.bdg /home/hyjforesight/mm10_chromInfo.txt /home/hyjforesight/bigWig/Cracd_KO1_treat_pileup_clip_sorted.bw
bedGraphToBigWig: error while loading shared libraries: libssl.so.1.0.0: cannot open shared object file: No such file or directory
```

**Expected behavior**
should generate bigWig smoothly

**Screenshots**
![image](https://user-images.githubusercontent.com/75048821/160263701-31365508-b725-4d82-9539-52195171c2ba.png)

**System (please complete the following information):**
 - OS: [Ubuntu 20.04]
 - MACS Version [3.0.0a7]

**Additional context**

**Comment by hyjforesight** [comment]
hello @taoliu 
Thanks for the solution! Now I can generate the bigWig from MACS3 peak files.
```linux
/home/hyjforesight/UCSC/bedGraphToBigWig /home/hyjforesight/bigWig/Cracd_KO1_treat_pileup_clip_sorted.bdg /home/hyjforesight/mm10_chromInfo.txt /home/hyjforesight/bigWig/Cracd_KO1_treat_pileup_clip_sorted.bw
```

I still have 2 questions. Appreciate it if you could kindly help me with these.
Q1. For `LC_COLLATE=C sort -k1,1 -k2,2n ${F}.clip > ${F}.sort.clip`, which code will be better, `LC_COLLATE=C` or `LC_ALL=C`?

Q2. I also generated another bigWig from the same sample by deeptools. BTW, both MACS3 and deeptools use the same sorted and shifted bam file.
```linux
bamCoverage -b /mnt/d/HYJ/shifted_postQC_sorted_Cracd_KO1.bam -o /home/hyjforesight/bigWig/Cracd_KO1.bw -of bigwig -bs 50 -p 16 --effectiveGenomeSize 2494787188 --normalizeUsing RPGC
```
Then I checked them in IGV. I found their peaks are a little bit different and a more significant difference is that peaks from MACS3 has lower value (0-7) than deeptools (0-17). What causes these differences and which bigWig shall I rely on?
![image](https://user-images.githubusercontent.com/75048821/160480032-b541d0b5-193c-49a5-984e-b8659f0e610a.png)

Thanks!
Best,
YJ

**Comment by taoliu** [comment]
`bedGraphToBigWig` is not part of MACS so I changed the category from `Bug Report` to `General Question`.

**Comment by maximilianh** [comment]
Hi @taoliu, I'm a member of the UCSC browser group. Let us know if we can do something to make the conversion of bedGraph files easier. I know that in the past these conversions have sometimes been tricky (e.g. the bedClip requirement). 

And just to state the obvious, bedSort does not use the LC variables, so @hyjforesight, don't worry about the variable if you use bedSort.

**Comment by hyjforesight** [comment]
I think many people face the same issue as I do. They may rely on the deeptools to make the bigWig. Hope this issue could be solved soon. Make it easier to convert begGraph from MACS.

**Comment by maximilianh** [comment]
I think the problem is conda, nothing that UCSC can change. You downloaded our binary and it worked. So this should probably be filed in the conda bugtracker here:  https://bioconda.github.io/recipes/ucsc-bedgraphtobigwig/README.html

**Comment by hyjforesight** [comment]
hello @taoliu 
Thanks for testing the `sort` and `bedSort`. I can help to add a comment on https://gist.github.com/taoliu/2469050 once the test is finished. Could be beneficial to other people.
Thanks!
Best,
YJ
