### ISSUE TITLE
broken link in readme

### ISSUE THREAD

**Issue by olechnwin** [macs3-project/MACS#506]
Just want to point out the link to [https://github.com/macs3-project/MACS/blob/master/docs/advanced_usage.md](https://github.com/macs3-project/MACS/blob/master/docs/advanced_usage.md) is broken.
It is the "advanced usage" link below subcommand table in readme.
![image](https://user-images.githubusercontent.com/20069067/161108441-5a633948-9af8-42cf-ac59-722bfce49b86.png)

Also, how can I find the advanced usage information?
Thanks!

**Comment by taoliu** [comment]
Please find the document for MACS2 here. Should be quite the same with MACS3. I need to make a MACS3 version for this though ... 
https://github.com/macs3-project/MACS/wiki/Advanced%3A-Call-peaks-using-MACS2-subcommands

**Comment by olechnwin** [comment]
Thanks! This works.
