### ISSUE TITLE
Q: What is meaning of 'local lambda value'?

### ISSUE THREAD

**Issue by dahun73** [macs3-project/MACS#512]
Hello !!

I have a question about 'local lambda value'. When using '--bdg' parameter, MACS will save bedGraph file of 'local lambda value'. 
![image](https://user-images.githubusercontent.com/52641420/172798936-c9cb3bf9-ae03-4ace-bcde-35771e50d2b4.png)

In this bedGraph file, what is the difference of bigWig file? Is it normalized or not?

I usually use 'makeUCSCfile' of HOMER or 'bamCoverage' of Deeptools for making coverage data. Because I don't know the exact meaning of 'local lambda value', I could not use this bedGraph format instead of other coverage data. 

Thank you in advance!!

**Comment by taoliu** [comment]
Hi @dahun73 , the file is in bedGraph format, which is a plain text file. If you set `-B`, you will get two files -- one for the treatment pileup and the other for control lambda values. They are used to generate the 'poisson p-values' which will be further used to call 'peaks'. You can read this wiki page on how to convert them to bigwig file for UCSC browser: https://github.com/macs3-project/MACS/wiki/Build-Signal-Track

And you can check this gist for the script to convert: https://gist.github.com/taoliu/2469050

**Comment by dahun73** [comment]
> Hi @dahun73 , the file is in bedGraph format, which is a plain text file. If you set `-B`, you will get two files -- one for the treatment pileup and the other for control lambda values. They are used to generate the 'poisson p-values' which will be further used to call 'peaks'. You can read this wiki page on how to convert them to bigwig file for UCSC browser: https://github.com/macs3-project/MACS/wiki/Build-Signal-Track
> 
> And you can check this gist for the script to convert: https://gist.github.com/taoliu/2469050

Thank you for kind explanation!! I will check it :)
