### ISSUE TITLE
Q: Script 'scripts/ceas' not found in metadata at None

### ISSUE THREAD

**Issue by aryan-dugar2** [macs3-project/MACS#526]
Hello,

I am working on a cloud server and trying to download CEAS. My procedure was,

```
wget `http://slackware.uk/sbosrcarch/by-name/academic/cistrome-CEAS/CEAS-Package-1.0.2.tar.gz
tar xvf CEAS-Package-1.0.2.tar.gz
cd CEAS-Package-1.0.2
python setup.py install --prefix=$HOME/.local
```

All of this works without issue. I get the package `ceas` installed in `$HOME/.local/bin/python3.7`. 
Now, I do

```
ml r/3.6.3
python --version
```

(I get Python 3.7.2 as the output)

and finally, to see if ceas works,

`$HOME/.local/bin/ceas `

However, this yields the output,

![image](https://user-images.githubusercontent.com/69087781/192599492-9fb08244-58da-456a-939c-65a222061951.png)

I am not sure why this is happening. Please let me know if you need anything else from my side. Thanks!

**Comment by taoliu** [comment]
The thing is that CEAS was made in old time for python2. I have a fork version under: https://github.com/taoliu/CEASp3 
 to make a python3 version of it but don't have time to finish it...

**Comment by aryan-dugar2** [comment]
Thanks for letting me know! I was able to get it working with the above instructions using Python 2.7
