### ISSUE TITLE
Import Error Undefined Symbol

### ISSUE THREAD

**Issue by yuelaiwang** [macs3-project/MACS#534]
When using macs2 package, I got a error like this. I saw an issue with the same error, but I cannot solve my problem with his solution.

> RuntimeError                              Traceback (most recent call last)
> File <timed eval>:1
> 
> File ~/anaconda3/envs/r4/lib/python3.9/site-packages/snapatac2/tools/_call_peaks.py:53, in call_peaks(adata, groupby, selections, q_value, out_dir, key_added, inplace)
>      51     groupby = list(adata.obs[groupby])
>      52 out_dir = out_dir if out_dir is None else str(out_dir)
> ---> 53 res = _snapatac2.call_peaks(adata, groupby, selections, q_value, out_dir)
>      54 if inplace:
>      55     if adata.isbacked:
> 
> RuntimeError: macs2 error:
> Traceback (most recent call last):
>   File "/home/shrestha/anaconda3/envs/r4/bin/macs2", line 653, in <module>
>     main()
>   File "/home/shrestha/anaconda3/envs/r4/bin/macs2", line 49, in main
>     from MACS2.callpeak_cmd import run
>   File "/home/shrestha/anaconda3/envs/r4/lib/python3.9/site-packages/MACS2/callpeak_cmd.py", line 23, in <module>
>     from MACS2.OptValidator import opt_validate
>   File "/home/shrestha/anaconda3/envs/r4/lib/python3.9/site-packages/MACS2/OptValidator.py", line 20, in <module>
>     from MACS2.IO.Parser import BEDParser, ELANDResultParser, ELANDMultiParser, \
>   File "MACS2/IO/Parser.pyx", line 25, in init MACS2.IO.Parser
>   File "MACS2/IO/FixWidthTrack.pyx", line 27, in init MACS2.IO.FixWidthTrack
>   File "MACS2/Pileup.pyx", line 19, in init MACS2.Pileup
>   File "MACS2/IO/BedGraph.pyx", line 26, in init MACS2.IO.BedGraph
> ImportError: /home/shrestha/anaconda3/envs/r4/lib/python3.9/site-packages/MACS2/IO/ScoreTrack.cpython-39-x86_64-linux-gnu.so: undefined symbol: __log_finite

How to solve this undefined symbol error?

**Comment by taoliu** [comment]
Likely linking issues to compiled macs2 libraries. First, test `macs2` in the command line to see if you can use it to call peaks from your data instead of running it within snapatac2. It's possible that MACS2 has to be reinstalled (remove the old installation entirely and install) by recompiling all these `so` files in this conda environment.

**Comment by yuelaiwang** [comment]
Thank you for the guidance!
