### ISSUE TITLE
Bug: swalign errors during setup

### ISSUE THREAD

**Issue by AinsleyisLife** [macs3-project/MACS#540]
**Describe the bug**

I've been struggling to get the package installed overall - latest issue is that when executing swalign during the setup process, it throws errors complaining about assigning arrays of unknown length / length 0:

```
MACS3/Signal/swalign.c(97): error C2057: Konstanter Ausdruck erwartet
MACS3/Signal/swalign.c(97): error C2466: Zuordnung eines Arrays der konstanten Größe 0 nicht möglich.
MACS3/Signal/swalign.c(97): error C2133: "reversed1": Unbekannte Größe
MACS3/Signal/swalign.c(98): error C2057: Konstanter Ausdruck erwartet
MACS3/Signal/swalign.c(98): error C2466: Zuordnung eines Arrays der konstanten Größe 0 nicht möglich.
MACS3/Signal/swalign.c(98): error C2133: "reversed2": Unbekannte Größe
MACS3/Signal/swalign.c(99): error C2057: Konstanter Ausdruck erwartet
MACS3/Signal/swalign.c(99): error C2466: Zuordnung eines Arrays der konstanten Größe 0 nicht möglich.
MACS3/Signal/swalign.c(99): error C2133: "reversed3": Unbekannte Größe
MACS3/Signal/swalign.c(339): error C2057: Konstanter Ausdruck erwartet
MACS3/Signal/swalign.c(339): error C2466: Zuordnung eines Arrays der konstanten Größe 0 nicht möglich.
MACS3/Signal/swalign.c(339): error C2133: "c": Unbekannte Größe
MACS3/Signal/swalign.c(339): error C2133: "d": Unbekannte Größe

```

Has anyone encountered this issue or got an idea of how to fix it?

**System (please complete the following information):**
 - OS: Windows 10
 - Python version 3.9.13
 - Numpy version 1.17
 - MACS Version 3.0.0

**Comment by philippadoherty** [comment]
Hi @AinsleyisLife, MACS is recommended to be used with either LinuxOS or MacOS, as Windows OS is not supported.

Similar issue: #444

**Comment by AinsleyisLife** [comment]
Hi, yes this was my conclusion too. 

I ended up running Ubuntu in a virtual shell via wsl and running the peak calling there. Can't say I'm a fan of analysing things  from the command line like it's 1983, but it worked!

Anyone else struggling to run Signac on windows, this is the way ^^
