### ISSUE TITLE
Bug: python3.12 incompatible due to numpy<1.24 restriction

### ISSUE THREAD

**Issue by jowodo** [macs3-project/MACS#598]
**Describe the bug**
numpy<1.26 does not work with python3.12 and macs3 needs numpy<1.24

Is it planned to upgrade the dependency of numpy so that macs3 can be used with python3.12?

**Comment by taoliu** [comment]
We will work on it. Thanks for the report!

**Comment by philippadoherty** [comment]
Hi @jowodo our requirements don't actually specify `numpy<1.24`, we only specify `numpy >= 1.19`. We tested this with Python version 3.12 and this works and passes our tests. MACS3 now supports Python versions 3.9, 3.10, 3.11, and 3.12 (x86_64). We are working on releasing a formal MACS 3.0.0 version soon, so keep an eye out for that. 

Please let us know if this is not resolved. Thanks

**Comment by jowodo** [comment]
My bad! I've added the numpy<1.24 previously to the installation procedure.
I removed it now. I tried to install macs3.0.0b3 with python3.9 as a test and it installed.
Installing macs3.0.0b3 with python3.12 gives me these errors
[log.txt](https://github.com/macs3-project/MACS/files/13364376/log.txt)
[err.txt](https://github.com/macs3-project/MACS/files/13364377/err.txt)

**Comment by philippadoherty** [comment]
Hi @jowodo, just to clarify, support for Python 3.12 will be available with the next release (3.0.0) that we are working on right now (not with macs3 3.0.0b3) - sorry for the confusion!

**Comment by jowodo** [comment]
aaah thanks for the clarification!

**Comment by philippadoherty** [comment]
no problem! We just released [MACS3 v3.0.0](https://github.com/macs3-project/MACS/releases/tag/v3.0.0) if you would like to try.

**Comment by jowodo** [comment]
installation was successful for python 3.9, 3.10, 3.11, 3.12 😎
