### ISSUE TITLE
Use of IDR after running MACS3 for ATAC-seq data

### ISSUE THREAD

**Issue by OrangeyO2** [macs3-project/MACS#599]
**Use case**
I am analyzing ATAC-seq data from human cells. I am planning to performed the following as part of my pipeline:

1. Adapter and T-overhang trimming with Cutadapt
2. Mapping to reference genome with bowtie2
3. PCR duplicate removal (Picard), quality and blacklist filtering (sambamba or samtools)
4. Peak calling with MACS3

**Describe the problem**
Looking at online pipelines, the use of IDR post peak calling with **MACS2** seems to be recommended.
_Is this still the case with the recently released **MACS3** v3.0.0_ when used with either the
default: macs3 callpeak -f BAMPE -t ATAC.bam -g hs -n test -B -q 0.01, or
hmmratac: macs3 hmmratac

Also, when IDR is used, MACS2 seems to be run with p-value cutoff of 0.1. If the use of IDR is still recommended post MACS3, should it be run with -p 0.1 as well?

Thanks in advance for your help!

**Comment by taoliu** [comment]
@OrangeyO2 Yes. You can still follow the pipeline for MACS2 -- using p-value cutoff 0.1 in `callpeak` command for IDR. The basic function of `callpeak` has minimum changes between MACS2 and MACS3.

**Comment by OrangeyO2** [comment]
@taoliu Thank you!
