### ISSUE TITLE
Bug: cython is required at build time but not install time

### ISSUE THREAD

**Issue by tillea** [macs3-project/MACS#606]
Hi,
as per some [Debian bug report](https://bugs.debian.org/1057991) cython is required to build the package but on the installed system it is not really needed.  I've fixed the Debian bug with this [patch](https://salsa.debian.org/med-team/macs/-/blob/master/debian/patches/no_install_depends_cython.patch) you might like to take over in your next release.
Kind regards, Andreas.

**Comment by philippadoherty** [comment]
Hi @tillea we are working on a minor release which will include this fix. 

Thanks

**Comment by tillea** [comment]
Am Wed, Jan 24, 2024 at 11:34:00AM -0800 schrieb Philippa Doherty:
> Hi @tillea we are working on a minor release which will include this fix. 
Thank you, Andreas.
