### ISSUE TITLE
Bug: pip install error: subprocess-exited-with-error

### ISSUE THREAD

**Issue by ferygood** [macs3-project/MACS#616]
**Describe the bug**
After creating a virtual environment using python -m venv myEnv and install MACS3 from pip, I get this subprocess-exited-with-error.

**To Reproduce**
1. Create a virtual environment using venv, i.e. python -m venv macs3
2. Run pip install MACS3

**Expected behavior**
I expect the software can be installed

**Screenshots**
Last lines in error message (see full file in attachement
[macs_install_error_log.txt](https://github.com/macs3-project/MACS/files/14096500/macs_install_error_log.txt)
):
```
       note: This error originates from a subprocess, and is likely not a problem with pip.
        ERROR: Failed building wheel for cykhash
      Failed to build cykhash
      ERROR: Could not build wheels for cykhash, which is required to install pyproject.toml-based projects
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× pip subprocess to install build dependencies did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```
**System (please complete the following information):**
 - OS: Debian12 (bookworm)
 - Python version 3.9.12
 - Numpy version No Numpy yet (due to fail installation of MACS3)
 - MACS Version MACS3

Thank you for your time and help!

**Comment by taoliu** [comment]
I read through your log, and it seems that you created a virtual python environment under your anaconda environment `/home/yaochung41/anaconda3/` and while compiling `cykash` which is the khash implemented by Cython, the compiler is also looking for C library files under the system root directory `/lib/x86_64-linux-gnu/libc.so.6`. It's like three or four different systems mixed together. I suggest you use your anaconda environment to create a dedicated conda environment through `conda env create...` then activate the conda environment and then install MACS3 there.

**Comment by ferygood** [comment]
Thank you, taoliu, for your response and explanation. It helps a lot and I have successfully installed MACS3 with conda.

solution shared:
```
# 1. create a conda environment with python 3.9
conda create -n macs3 python=3.9  

# 2. install macs3 from pypi
pip install macs3 
```
