### ISSUE TITLE
MACS3 callpeak does not create UCSC Browser ready peak files

### ISSUE THREAD

**Issue by callum-b** [macs3-project/MACS#653]
The [MACS3 docs](https://macs3-project.github.io/MACS/docs/callpeak.html) state that callpeaks create Peak files that are compatible with the UCSC browser, but when I try to upload mine, the 7th-10th values raise errors. From the docs it looks like callpeaks is supposed ot create a track header in the file, but this is not the case. 

Was this fixed in a later version? Did I miss an option for MACS3.0.0

command used: `macs3 callpeak -f BED -t DATA/BED/CTCF_H3K9ac/H3K9ac_T7_neg_3_filterdup_filterchr.bed -c DATA/BED/CTCF_H3K9ac/Input_T7_neg_filterdup_filterchr.bed -n H3K9ac_T7_neg_3 --outdir DATA/PEAKS/CTCF_H3K9ac/ --nomodel --extsize 121 -g hs -q 0.01 2>snakemake_logs/macs3_callpeak/CTCF_H3K9ac_H3K9ac_T7_neg_3.log`

 - MACS Version 3.0.0
 
![narrow peak no header](https://github.com/user-attachments/assets/b2874e60-8229-49f2-9a7a-50bba56a7a4d)

![narrow peak ucsc error](https://github.com/user-attachments/assets/769a0afd-5a9f-4df1-a277-5cf225c64844)

**Comment by taoliu** [comment]
Hi @callum-b We will add this trackline to the narrowPeak output while '--trackline' option is on. Thank you!
