### ISSUE TITLE
Bug: Are requirements stated correctly?

### ISSUE THREAD

**Issue by outpaddling** [macs3-project/MACS#658]
I'm wondering if the requirements stated in requirements.txt and pyproject.toml are accurate.

Under FreeBSD ports, MACS3 seems to build and run fine using Cython 0.29.37, scipy 1.11.1, and setuptools 63.0.  Just giving a heads-up because overstating the requirements might delay or prevent addition of MACS3 to some package managers, where dependencies lag behind the latest due to other dependent packages. 

Below is one of the patches I incorporated into the FreeBSD port to get MACS 3.0.2 running.

```
--- requirements.txt.orig       2024-09-07 16:11:35 UTC
+++ requirements.txt
@@ -1,8 +1,8 @@
-Cython>=3.0,<3.1
+Cython>0
 numpy>=1.25,<2.0.0
-scipy>=1.12
+scipy>=1.11.1
 scikit-learn>=1.3
 hmmlearn>=0.3.2
 cykhash>=2.0,<3.0 
 pytest>=7.0
-setuptools>=68.0
+setuptools>=63.0
```

**Comment by taoliu** [comment]
@outpaddling Thanks for your information! We don't have the capacity to test all possible versions and combinations for backward compatibility, so that's why I tried to put the most recent libraries that we have tested. Since it runs fine, the patched requirements.txt is good for me. One change: please use Cython>=0.29.37 if it's possible.

**Comment by outpaddling** [comment]
OK, here are the updated patches:

```
--- requirements.txt.orig       2024-09-07 16:11:35 UTC
+++ requirements.txt
@@ -1,8 +1,8 @@
-Cython>=3.0,<3.1
+Cython>=0.29.37
 numpy>=1.25,<2.0.0
-scipy>=1.12
+scipy>=1.11.1
 scikit-learn>=1.3
 hmmlearn>=0.3.2
 cykhash>=2.0,<3.0 
 pytest>=7.0
-setuptools>=68.0
+setuptools>=63.0
```
```
--- pyproject.toml.orig 2024-09-07 16:11:35 UTC
+++ pyproject.toml
@@ -1,3 +1,3 @@
 [build-system]
-requires=['setuptools>=68.0', 'numpy>=1.25,<2.0.0', 'scipy>=1.12', 'cykhash>=2.0,<3.0', 'Cython>=3.0,<3.1', 'scikit-learn>=1.3', 'hmmlearn>=0.3.2']
+requires=['setuptools>=63.0', 'numpy>=1.25,<2.0.0', 'scipy>=1.11.1', 'cykhash>=2.0,<3.0', 'Cython>=0.29.37', 'scikit-learn>=1.3', 'hmmlearn>=0.3.2']
```
