### ISSUE TITLE
Q: does BAMPE format require a name-sorted BAM or coordinate-sorted bam or it does not matter? 

### ISSUE THREAD

**Issue by sotuamax** [macs3-project/MACS#661]
Hello, 

I have a general question about the BAMPE format run for peakcall using MACS3. It seems like the document doesnot indicate the specific format for BAMPE as either name-sorted or coordinate-sorted. Could you clarify it here? 

Many thanks!

Best,

**Comment by taoliu** [comment]
@sotuamax As for the BAMPE file for `callpeak` and `hmmratac` function, sorting is not required.

**Comment by sotuamax** [comment]
thank you for your clarification.
