### ISSUE TITLE
Docs: "Install from source" guide is broken

### ISSUE THREAD

**Issue by aowenson-imm** [macs3-project/MACS#674]
In [Install from source through pip](https://macs3-project.github.io/MACS/docs/INSTALL.html#install-from-source-through-pip) you say to run:

> git clone --recurse-submodules git@github.com:macs3-project/MACS.git

Fails for me:

```
Cloning into 'MACS'...
The authenticity of host 'github.com (20.26.156.215)' can't be established.
ED25519 key fingerprint is SHA256:+<redacted>.
This key is not known by any other names
Are you sure you want to continue connecting (yes/no/[fingerprint])? yes
Warning: Permanently added 'github.com' (ED25519) to the list of known hosts.
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.
```

Why not just do this?
> git clone --recurse-submodules https://github.com/macs3-project/MACS.git

**Comment by taoliu** [comment]
Thanks! I just fixed it.
