### ISSUE TITLE
macs2 BAMPE parser and samtools rmdup

### ISSUE THREAD

**Issue by jurgjn** [macs3-project/MACS#68]
I'm calling peaks on paired-end data with macs2 callpeaks --format BAMPE, and using samtools rmdup to remove potential PCR duplicates beforehand.

Samtools rmdup only works on "FR orientation" alignments, obtained via [checking for isize > 0](https://github.com/samtools/samtools/blob/fcb8af08a6fd3bfcf195407c4ba5bae528ee326d/bam_rmdup.c#L152). The BAMPE parser in macs2 constructs the pileup by only [considering alignments that are "first in sequencing"](https://github.com/taoliu/MACS/blob/87e287d88a557cfabb8c021c3c2f40d137f8dd9f/MACS2/IO/cParser.pyx#L1233-L1250).

Both criteria can be used to iterate over an alignment of paired-end tags such that one only considers every fragment in the sequenced library once. However, as the sign of isize and whether a tag is "first in sequencing" are independent of each other, using both discards half of the signal.

Assuming the above makes sense, would it be worth changing the BAMPE parser in macs2 to use the same criteria as samtools (=filter for isize > 0)? Technically this looks straightforward and I'm happy to contribute a patch, but I wanted to make sure that I haven't missed anything obvious...

Kind regards,
Jürgen

**Comment by philippadoherty** [comment]
Closing this issue as "stale" due to inactivity.
