### ISSUE TITLE
Comparing BAM vs BAMPE mode

### ISSUE THREAD

**Issue by vivekbhr** [macs3-project/MACS#81]
Hi

I was comparing macs results for my protein in BAM vs BAMPE mode (my data is paired-end) and found the differences in results which I couldn't explain.
BAMPE mode gives much more peaks than BAM mode (about 1/3rd more than BAM mode), and also a lot of peaks in the smaller set (BAM mode) don't overlap with those in larger set. I looked at the unique peaks from either set in IGV and couldn't spot any difference. Both these peaks seem to have a moderate (not much enrichment) compared to input. Common detected peaks seem to have more enrichment than peaks detected uniquely by each. 

Can you explain this discrepancy and suggest which one is a better set to work with? This seems to be due to the difference in local lambda calculated using fragment size, but since in both cases it's automatically calculated, which one is more reliable?

Thanks a lot
Vivek

**Comment by philippadoherty** [comment]
Closing this issue as "stale" due to inactivity.
