### ISSUE TITLE
BAMPE

### ISSUE THREAD

**Issue by salviadr** [macs3-project/MACS#92]
HI tao
 I am a freshman in CHIP-seq.I have some problems about macs2.In macs2 readme file,I found that "BAMPE" is a different parameter in macs14 and macs2.Is macs2 strictly distinguished from the data format? I had ran macs14 yet,now i want to try macs2.For PE data,i must set the "BAMPE" parameter? If I do not set the parameters of "-f" to "BAMPE", the analysis results will be very different? Will not be accurate?In addition, I have noticed that there is a regular peak calling analysis and a broad peak calling analysis of macs2.Is the analysis of the broad peak is a development of macs2?Is it necessary for me to analyse the regular peak and broad peak at sametime?

Best
salviadr

**Comment by rat-codes** [comment]
If the input reads are paired-end, MACS2 will skip the model building step for estimating the fragment size. So, when you specify -f BAMPE option, MACS2 records the fragment size information from the TLEN field (column 9) in your BAM file (Note that MACS2 will only use reads mapped in proper pair, and will filter out duplicate pairs). 

The choice of using a narrow peak calling (regular) or broad peak calling depends on your protein type. People usually use narrow peaks (regular) for TF, broad peaks for Histone modifications, and both for RNAPOL 2 marks. 

-Aarthi

**Comment by philippadoherty** [comment]
Closing this issue as "stale" due to inactivity.
