### ISSUE TITLE
hypermethylation vs. hypomethylation assessment 

### ISSUE THREAD

**Issue by burtontimothy** [macs3-project/MACS#96]
I hope this is the right venue for this question, if not please let me know where I can direct it. I have paired samples (tumour & control) that have been sequenced for methylation. I'd like to assess hypermethylation and hypomethylation in the tumour versus the control, would the following commands be valid? I've switched control and treated to look at hypomethylation. 

hypermethylation: callpeak -f BAM -t treated.bam -c control.bam
hypomethylation: callpeak -f BAM -t control.bam -c treated.bam

**Comment by swernig** [comment]
If you don't have input for tumour and control samples (which would be ideal), than yes this would be a way to do it.
