### ISSUE TITLE
question about RNApolymerase II chipseq data

### ISSUE THREAD

**Issue by chenzizhen** [macs3-project/MACS#99]
Hi,

i'm dealing with RNApolyII chipseq data using MACS2.

RNApolyII chipseq data contains two kinds of peaks:narrow peaks at TSS region and broad peaks across genebody.

so,how to set options of MACS2?

DO i have to run MACS2 twice? first,run macs2 callpeak without --broad in order to find narrow peaks at TSS. Then run macs2 with --broad to find broad peaks? 

If I do that, should I run MACS2 bdgdiff separately if I want to find difference  between two different samples?
Best
chenzizhen

**Comment by melnuesch** [comment]
I wanted to ask the same: is MACS2 broad suitable for mixed-type peak calling?

**Comment by philippadoherty** [comment]
Closing this issue as "stale" due to inactivity.
